### ISSUE TITLE
exec /usr/bin/microbin: exec format error

### ISSUE THREAD

**Issue by Danie10** [dvdsk/microbin#18]
**Describe the bug**
Docker container shows just:
`exec /usr/bin/microbin: exec format error`

**To Reproduce**
1. Checked configs from original Microbin. Looked all the same so nothing changed.
2. Changed image line in docker compose to `image: uniquepwd/microbin:latest`.
3. Pulled new image and started container.
4. Container starts but no webpage.
5. See error in logs.

**Expected behavior**
Service to start with accessible webpage.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Manjaro KDE Plasma
 - Browser Firefox
 - Version v141.0

**Additional context**
If I switch back to original image (image: uniquepwd/microbin:latest) it starts fine.
Using SQLite database

**Comment by yara-blue** [comment]
@Danie10 Thanks for the great report! We just merged some fixes by @UniquePWD could you retry and see if those fix things?

**Comment by Danie10** [comment]
@dvdsk nope still get the same error. I did re-pull the image as well. But I see the Github project here still only shows yesterday's update v.2.0.0 I think it is. Not sure if maybe I did not yet get the latest image update.

**Comment by yara-blue** [comment]
Whats the output of (the linux command) `uname -m`? Can you run from source? (install rust, clone repo, `cargo run` inside repor root)

**Comment by uniquePWD** [comment]
Looked into this a bit, it looks like you're grabbing the wrong image.

Can you try and set the image to `docker pull ghcr.io/dvdsk/microbin:latest@sha256:5298aa1512fd838214f62747b1d943f25cc126af81863a8f7e9e4c0405faa291`

And tell me if you still have issues?

**Comment by Danie10** [comment]
OK getting same error if I pull that other image as well.

This is the output though that I get if I'm running the pre-fork original (can't log into the new image's container as it is always restarting):
```
root@microbin:/app# uname -m
x86_64
```

**Comment by Danie10** [comment]
@dvdsk no that is going to be quite a mission and I'm using containers to keep my VPS cleaner. I did check the configs and .env and everything looked the same (apart from obviously my own specific values). The thing is as soon as I switch back to the original image, it runs perfectly. So I did no migration commands or anything.

**Comment by uniquePWD** [comment]
> OK getting same error if I pull that other image as well.
> 
> This is the output though that I get if I'm running the pre-fork original (can't log into the new image's container as it is always restarting):
> 
> ```
> root@microbin:/app# uname -m
> x86_64
> ```

Ok, the problem is that we don't have an x86_64 build.

@SamTV12345 can you trigger a new round of builds and include an x86_64 image please? We'll call that the official 2.1.0 release to ensure this fork is properly differentiated.

**Comment by SamTV12345** [comment]
I'll check after work. I'm wondering why we don't have a x86 build. It took so long to build the image and I didn't change something there.

**Comment by SamTV12345** [comment]
I'll check after work. I'm wondering why we don't have a x86 build. It took so long to build the image and I didn't change something there.

**Comment by uniquePWD** [comment]
> I'll check after work. I'm wondering why we don't have a x86 build. It took so long to build the image and I didn't change something there.

I suspect the unknown/unknown build is the x86_64 build and there was a build error of some sort.

**Comment by SamTV12345** [comment]
> **Describe the bug** Docker container shows just: `exec /usr/bin/microbin: exec format error`
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Checked configs from original Microbin. Looked all the same so nothing changed.
> 2. Changed image line in docker compose to `image: uniquepwd/microbin:latest`.
> 3. Pulled new image and started container.
> 4. Container starts but no webpage.
> 5. See error in logs.
> 
> **Expected behavior** Service to start with accessible webpage.
> 
> **Screenshots** N/A
> 
> **Desktop (please complete the following information):**
> 
> * OS: Manjaro KDE Plasma
> * Browser Firefox
> * Version v141.0
> 
> **Additional context** If I switch back to original image (image: uniquepwd/microbin:latest) it starts fine. Using SQLite database

For now it is fixed and you can use our own image ghcr.io/dvdsk/microbin:latest. I'll check why the image does not build

**Comment by SamTV12345** [comment]
> > I'll check after work. I'm wondering why we don't have a x86 build. It took so long to build the image and I didn't change something there.
> 
> I suspect the unknown/unknown build is the x86_64 build and there was a build error of some sort.

Could you show me how you build the image?

**Comment by Danie10** [comment]
@SamTV12345 perfect thanks that worked 100% now!

**Comment by uniquePWD** [comment]
> > > I'll check after work. I'm wondering why we don't have a x86 build. It took so long to build the image and I didn't change something there.
> > 
> > 
> > I suspect the unknown/unknown build is the x86_64 build and there was a build error of some sort.
> 
> Could you show me how you build the image?

I just build locally 

```
docker build --no-cache --pull -t microbin:latest .
docker tag microbin:latest uniquepwd/microbin:latest
```
